### ISSUE TITLE
Instructor Feedback - Week 5 work

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [stasRevin/danceUpByStas#2]
What a great start you have on the relationships and hibernate. 

- [x] I agree that you will need a UserDance entity since there are additional columns on the User_Dance table. However, you should not need the UserRole entity and UserLesson entities, as there are not additional columns on the related join table (at least not in the design documents in github). The @ManyToMany annotation will work. Here's are a couple article which may help: https://www.baeldung.com/hibernate-many-to-many and http://www.mkyong.com/hibernate/hibernate-many-to-many-relationship-example-annotation/
- [x] I think you should be able to get rid of a few of your entity daos, by implementing a "find by property method" in the generic dao. For a hint on how you might add that method to the generic dao, refer to this example: https://github.com/rodrigouchoa/generic-dao/blob/master/src/main/java/com/rodrigouchoa/generic/dao/GenericDaoHibernate.java

**Comment by stasRevin** [comment]
Thank you for the feedback. This is a great point. The reason why I did it was because of that chapter in Head First Java where they were comparing procedural style with object-oriented one (not to say that you're suggesting procedural style). They brought an argument that one of the reasons why OOP is better was because it is extensible and even though, in their example, the object-oriented developer spent more time in the beginning on adding all those classes, seeming to have redundant and duplicate code vs straightforwardness of the procedural style. But as soon as the project manager started changing requirements, the object-orientation saved a lot of time in making updates. In my project, at this point, the linked tables do not indeed have any extra columns, but what if right before the project release, the manager comes to me and says: "Hey, you know what, we think it would be nice to display the date when users started on our platform as an instructor or a student to remind them of the time invested in our product and improve our chances to keep them around longer." In that case, I'll just add one extra field into user_role (date joined as instructor or student)table and one extra field into UserRole class plus a few minor updates. But if I have @many-to-many, then I'll need to add an extra class, change my annotations in that node, rewrite the test code, update the DAO methods, etc. Some shops also like to have a surrogate key on all of their tables even on joined ones - adding that will be easy as well. Anyways, I'll change it to @many-to-many if this is a project requirement. Thank you.

**Comment by stasRevin** [comment]
I provided the comments into my many-to-many entities to explain the reasoning behind additional entities. The commit id with the comments is e98c5fba07fb744c060e8e20d566591f428714d1.
Thank you for the feedback, I learned a lot by comparing different ways how it can be done and reasoning through it.

**Comment by stasRevin** [comment]
Almost forgot, here is the update to the Generic DAO. I placed more methods to Generic Dao and got rid of unnecessary DAOs. I still kept test DAO-specific, just so I know what instance of Generic Dao I am testing. The commit for that is here c843af2c4557203cf6029fa854fa44ce5222ea19.
Thank you, that cleaned my project pretty well.
